$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
display_name: used-cars-price-prediction-pipeline
experiment_name: used-cars-experiment
description: Pipeline for training and registering used cars price prediction model

inputs:
  raw_data:
    type: mltable 
    path: azureml:used-cars-data@latest

outputs:
  train_data:
    type: mltable 
  test_data:
    type: mltable
  model_info_output_path:
    type: uri_folder

settings:
  default_datastore: azureml:workspaceblobstore
  default_compute: azureml:cpu-cluster
  continue_on_step_failure: false

jobs:
  prep_data:
    name: data_preparation
    display_name: data-preparation-step
    code: ../../../data-science/src
    command: >-
      python prep.py
      --raw_data ${{inputs.raw_data}}
      --train_data ${{outputs.train_data}}
      --test_data ${{outputs.test_data}}
    environment: azureml:used-cars-train-env@latest
    inputs:
      raw_data: 
        type: mltable
        source: ${{parent.inputs.raw_data}}
    outputs:
      train_data:
        type: mltable
        destination: ${{parent.outputs.train_data}}
      test_data:
        type: mltable
        destination: ${{parent.outputs.test_data}}

  sweep_step:
    name: hyperparameter_tuning
    display_name: hyperparameter-tuning-step
    type: sweep
    inputs:
      train_data:
        type: mltable
        source: ${{parent.jobs.prep_data.outputs.train_data}}
      test_data:
        type: mltable
        source: ${{parent.jobs.prep_data.outputs.test_data}}
    outputs:
      model_output:
        type: mlflow_model
    sampling_algorithm: random
    trial: 
      type: command 
      command: python train.py --train_data ${{inputs.train_data}} --test_data ${{inputs.test_data}}
    search_space:
      n_estimators: 
        type: choice
        values: [30]  
      max_depth: 
        type: choice
        values: [10]  
    objective:
      goal: minimize
      primary_metric: MSE
    limits:
      max_total_trials: 20
      max_concurrent_trials: 10
      timeout: 7200

  register_model:
    name: register_trained_model
    display_name: model-registration-step
    code: ../../../data-science/src
    command: >-
      python register.py
      --model_name "used_cars_price_prediction_model" 
      --model_path ${{inputs.model_path}}
      --model_info_output_path ${{outputs.model_info_output_path}}
    environment: azureml:used-cars-train-env@latest
    inputs:
      model_path:
        type: mlflow_model
        source: ${{parent.jobs.sweep_step.outputs.model_output}}
    outputs:
      model_info_output_path:
        type: uri_folder
        destination: ${{parent.outputs.model_info_output_path}}
